services:
  adameds_frontend:
    container_name: adameds-frontend
    image: adameds-frontend:dev
    build: 
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 5520:5520
    networks:
      - adameds-bridge-networks
    restart: always
networks:
  adameds-bridge-networks:
    driver: bridge
