import { defineStore } from 'pinia';
import { ref } from 'vue';

export const usePermissionStore = defineStore('permission', () => {
  // Define permissions
  const permissionsItem = ref([
    {
      module: "Antrian",
      subModules: [
        {
          name: "Konfigurasi",
          allows: ["READ", "CREATE", "UPDATE", "DELETE"],
        },
        {
          name: "Data Antrian",
          allows: ["READ"],
        },
        {
          name: "Layar",
          allows: ["READ"],
        },
        {
          name: "Apm",
          allows: [
            "CREATE PASIEN JKN",
            "CREATE PASIEN NON-JKN",
            "CHECKIN",
            "PRINT",
          ],
        },
      ],
    },
    {
      module: "Admisi",
      subModules: [
        {
          name: "Antrian",
          allows: ["PANGGIL", "LEWATI", "PROSES", "SELESAI", "CHECKIN"],
        },
        {
          name: "RJ",
          allows: [
            "READ",
            "CREATE PASIEN RJ",
            "CREATE GENERAL CONSENT",
            "UPDATE ADMISI RJ",
            "UPDATE GENERAl CONSENT",
            "CETAK KUNJUNGAN",
            "CETAK LABEL",
            "BATAL RJ",
          ],
        },
        {
          name: "RI",
          allows: [
            "READ",
            "CREATE BAYI BARU LAHIR",
            "CREATE GENERAL CONSENT",
            "UPDATE ADMISI RI",
            "UPDATE GENERAL CONSENT",
            "BATAL REQUEST RI",
            "CETAK GENERAL CONSENT",
            "CETAK KUNJUNGAN",
            "CETAK LABEL",
          ],
        },
        {
          name: "IGD",
          allows: [
            "READ",
            "CREATE PASIEN IGD",
            "CREATE GENERAL CONSENT",
            "UPDATE ADMISI IGD",
            "UPDATE GENERAL CONSENT",
            "BATAL IGD",
            "CETAK GENERAL CONSENT",
            "CETAK KUNJUNGAN",
            "CETAK LABEL",
          ],
        },
        {
          name: "SEP",
          allows: [
            "READ",
            "CREATE SEP",
            "CREATE SEP MANUAL",
            "DELETE SEP",
            "SIMPAN SEP MANUAL",
          ],
        },
        {
          name: "Data Pasien",
          allows: [
            "READ",
            "CREATE PASIEN",
            "UPDATE BERKAS RM",
            "UPDATE DATA PASIEN",
            "DELETE PASIEN",
            "DELETE BERKAS RM",
            "IMPORT DATA PASIEN",
            "CETAK KARTU PASIEN",
            "UPLOAD BERKAS RM",
            "PREVIEW BERKAS RM",
            "GENERAL CONSENT",
          ],
        },
        {
          name: "Monitoring Kamar",
          allows: ["READ", "SETTING BED", "CREATE BED", "DELETE BED"],
        },
        {
          name: "Laporan Admisi",
          features: [
            {
              name: "Kunjungan",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "penjamin",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Batal Kunjungan",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Status kamar",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Keperawatan Inap Pasien",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Bayi Baru Lahir",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Rekap Jumlah Pasien BPJS",
              allows: ["READ", "CETAK LAPORAN"],
            },
          ],
        },
      ],
    },
    {
      module: "Rawat Jalan",
      subModules: [
        {
          name: "Antrian",
          allows: ["PANGGIL", "LEWATI", "PROSSES", "SELESAI"],
        },
        {
          name: "Poli",
          allows: ["READ", "BATAL KUNJUNGAN"],
        },
        {
          name: "BPJS-PCARE",
          features: [
            {
              name: "Monitoring Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
            {
              name: "Monitoring Riwayat Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
            {
              name: "Monitoring Obat Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
          ],
        },
        {
          name: "Laporan Rawat Jalan",
          features: [
            {
              name: "Kunjungan",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Pembatalan Poli",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "rekap Pembatalan Pasien",
              allows: ["READ", "CETAK LAPORAN"],
            },
          ],
        },
        {
          name: "RME",
          features: [
            {
              name: "Rekap Medis",
              allows: [
                "READ",
                "UPDATE PEMERIKSAAN GIGI",
                "UPDATE PEMERIKSAAN MATA",
                "UPDATE PEMERIKSAAN FISIK",
                "UPDATE DERAJAT LUKA BAKAR",
                "UPDATE PEMERIKSAAN DAN TINDAKAN",
                "UPDATE REKAM MEDIS",
                "CETAK LABEL",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TAMPILKAN DETAIL PASIEN",
              ],
            },
            {
              name: "Asemen",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TIDAK ADA ALERGI",
                "CREATE ALERGI",
                "CREATE ANAMNESIS",
                "CREATE TANDA VITAL",
                "CREATE ANTROPOMETRI",
                "CREATE ASESMEN NYERI",
                "CREATE KESADARAN",
                "CREATE PEMERIKSAAN FISIK",
                "CREATE PEMERIKSAAN GIGI",
                "CREATE PEMERIKSAAN MATA",
                "CREATE DERAJAT LUKA BAKAR",
                "CREATE CATATAN HASIL PENUNJANG",
                "CREATE DIAGNOSIS DOKTER",
                "CREATE ASUHAN KEPERAWATAN",
                "CREAT CATATAN PERAWAT",
                "CREATE INSTRUKSI MEDIS",
                "CREATE PEMERIKSAAN DAN TINDAKAN",
              ],
            },
            {
              name: "SOAP",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CREATE OBAT",
                "CREATE OBAT RACIKAN",
                "UPDATE OBAT",
                "DELETE OBAT",
              ],
            },
            {
              name: "Akses Dan Penunjang",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "CREATE ALKES",
                "CREATE ALKES MULTIPLE",
                "DELETE LIST ALKES",
                "DELETE ITEM ALKES MULTIPLE",
                "DELETE SEMUA",
                "AMBIL ITEM",
                "SIMPAN ORDER",
                "CREATE TINDAKAN",
                "DELETE LIST TINDAKAN",
              ],
            },
            {
              name: "Inform Consent",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "CREATE",
              ],
            },
            {
              name: "Unggah Berkas",
              allows: [
                "READ",
                "UPDATE FILE TERUNGGAH",
                "DELETE FILE TERUNGGAH",
                "CETAK LABEL",
                "RIWAYAT",
                "MENYEMBUNYIKAN DETAIL PASIEN",
                "CARI FILE",
                "TAMPILAN LIST",
                "TAMPILAN GRID",
              ],
            },
            {
              name: "Resume Dan Discarge",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CETAK RESUME MEDIS",
                "SIMPAN RESUME MEDIS",
                "DISCHARGE",
              ],
            },
            {
              name: "Cetak Hasil Dan Surat",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CETAK HASIL",
                "CREATE SURAT",
                "DELETE SURAT KETERANGAN",
                "CETAK SURAT",
              ],
            },
          ],
        },
      ],
    },
    {
      module: "Rawat Inap",
      subModules: [
        {
          name: "Rawat Inap",
          allows: ["READ", "BATAL DIRAWAT"],
        },
        {
          name: "Perpindahan Bangsal",
          allows: ["READ", "BATAL TERIMA", "SETUJU DAN TERIMA"],
        },
        {
          name: "BPJS-PCARE",
          features: [
            {
              name: "Monitoring Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
            {
              name: "Monitoring Riwayat Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
            {
              name: "Monitoring Obat Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
          ],
        },
        {
          name: "Laporan",
          features: [
            {
              name: "Monitoring Rawat Inap",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Perpindahan Pasien",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Pembatalan Berobat",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Rekap Tindakan Pasien",
              allows: ["READ", "CETAK LAPORAN"],
            },
          ],
        },
        {
          name: "Detail Pasien",
          features: [
            {
              name: "Rekam Medis",
              allows: [
                "READ",
                "UPDATE PEMERIKSAAN FISIK",
                "UPDATE DERAJAT LUKA BAKAR",
                "UPDATE PEMERIKSAAN DAN TINDAKAN",
                "UPDATE REKAM MEDIS",
                "DELETE SESI",
                "CETAK LABEL",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TAMPILKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "RIWAYAT",
              ],
            },
            {
              name: "Asesmen",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "TIDAK ADA ALERGI",
                "CREATE ALERGI",
                "CREATE ANAMNESIS",
                "CREATE TANDA VITAL",
                "CREATE ANTROPOMETRI",
                "CREATE ASESMEN NYERI",
                "CREATE KESADARAN",
                "CREATE PEMERIKSAAN FISIK",
                "CREATE DERAJAT LUKA BAKAR",
                "CREATE CATATAN HASIL PENUNJANG",
                "CREATE DIAGNOSIS DOKTER",
                "CREATE ASUHAN KEPERAWATAN",
                "CREATE CATATAN PERAWAT",
                "CREATE INSTRUKSI MEDIS",
                "CREATE PEMERIKSAAN DAN TINDAKAN",
              ],
            },
            {
              name: "SOAP Dokter",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CREATE OBAT",
                "CREATE OBAT RACIKAN",
                "UPDATE OBAT",
                "DELETE OBAT",
              ],
            },
            {
              name: "Inform Consent",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CREATE",
              ],
            },
            {
              name: "Alkes Dan Penunjang",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "CREATE ALKES",
                "CREATE ALKES MULTIPLE",
                "DELETE ALKES",
                "DELETE ALKES MULTIPLE",
                "DELETE SEMUA",
                "AMBIL ITEM",
                "SIMPAN ORDER",
                "CREATE TINDAKAN",
              ],
            },
            {
              name: "Perpindahan",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "PINDAHKAN PASIEN",
              ],
            },
            {
              name: "FPO",
              allows: [
                "READ",
                "CREATE PEMBERIAN OBAT",
                "UPDATE PEMBERIAN OBAT",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TANGGAL PEMERIKSAAN",
                "TANGGAL PEMBERIAN OBAT",
              ],
            },
            {
              name: "Unggah Berkas",
              allows: [
                "READ",
                "UPDATE FILE TERUNGGAH",
                "DELETE FILE TERUNGGAH",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "CARI FILE",
                "TAMPILAN LIST",
                "TAMPILAN GRID",
              ],
            },
            {
              name: "Resume & Discharge",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CETAK RESUME MEDIS",
                "SIMPAN RESUME MEDIS",
                "DISCHARGE",
              ],
            },
            {
              name: "Cetak Hasil & Surat",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CETAK HASIL",
                "CREATE SURAT",
                "DELETE SURAT KETERANGAN",
                "CETAK SURAT",
              ],
            },
          ],
        },
      ],
    },
    {
      module: "IGD",
      subModules: [
        {
          name: "IGD",
          allows: ["READ", "BATAL DIRAWAT"],
        },
        {
          name: "BPJS-PCARE",
          features: [
            {
              name: "Monitoring Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
            {
              name: "Monitoring Riwayat Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
            {
              name: "Monitoring Obat Kunjungan",
              allows: ["READ", "CETAK BPJS"],
            },
          ],
        },
        {
          name: "Laporan IGD",
          features: [
            {
              name: "Kunjungan",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Pembatalan Berobat",
              allows: ["READ", "CETAK LAPORAN"],
            },
            {
              name: "Rekap Tindakan Pasien",
              allows: ["READ", "CETAK LAPORAN"],
            },
          ],
        },
        {
          name: "Detail Pasien",
          features: [
            {
              name: "Rekam Medis",
              allows: [
                "READ",
                "UPDATE PEMERIKSAAN FISIK",
                "UPDATE DERAJAT LUKA BAKAR",
                "UPDATE PEMERIKSAAN DAN TINDAKAN",
                "UPDATE REKAM MEDIS",
                "DELETE SESI",
                "CETAK LABEL",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TAMPILKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "RIWAYAT",
              ],
            },
            {
              name: "Asesmen",
              allows: [
                "READ",
                "CETAK LABEL",
                "SEMBUNYIKAN DETAIL PASIEN",
                "RIWAYAT",
                "TIDAK ADA ALERGI",
                "CREATE ALERGI",
                "CREATE ANAMNESIS IGD",
                "CREATE TRIASE",
                "CREATE TANDA VITAL",
                "CREATE ANTROPOMETRI",
                "CREATE ASESMEN NYERI",
                "CREATE KESADARAN",
                "CREATE PEMERIKSAAN FISIK",
                "CREATE DERAJAT LUKA BAKAR",
                "CREATE CATATAN HASIL PENUNJANG",
                "CREATE DIAGNOSIS DOKTER",
                "CREATE ASUHAN KEPERAWATAN",
                "CREATE CATATAN PERAWAT",
                "CREATE INSTRUKSI MEDIS",
                "CREATE PEMERIKSAAN DAN TINDAKAN",
              ],
            },
            {
              name: "SOAP Dokter",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CREATE OBAT",
                "CREATE OBAT RACIKAN",
                "UPDATE OBAT",
                "DELETE OBAT",
              ],
            },
  
            {
              name: "Alkes Dan Penunjang",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "CREATE ALKES",
                "CREATE ALKES MULTIPLE",
                "DELETE ALKES",
                "DELETE ALKES MULTIPLE",
                "DELETE SEMUA",
                "AMBIL ITEM",
                "SIMPAN ORDER",
                "CREATE TINDAKAN",
              ],
            },
            {
              name: "Inform Consent",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CREATE",
              ],
            },
            {
              name: "FPO",
              allows: [
                "READ",
                "CREATE PEMBERIAN OBAT",
                "UPDATE PEMBERIAN OBAT",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TANGGAL PEMERIKSAAN",
                "TANGGAL PEMBERIAN OBAT",
              ],
            },
            {
              name: "Unggah Berkas",
              allows: [
                "READ",
                "UPDATE FILE TERUNGGAH",
                "DELETE FILE TERUNGGAH",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "CARI FILE",
                "TAMPILAN LIST",
                "TAMPILAN GRID",
              ],
            },
            {
              name: "Resume & Discharge",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CETAK RESUME MEDIS",
                "SIMPAN RESUME MEDIS",
                "DISCHARGE",
              ],
            },
            {
              name: "Cetak Hasil & Surat",
              allows: [
                "READ",
                "CETAK LABEL",
                "RIWAYAT",
                "SEMBUNYIKAN DETAIL PASIEN",
                "TUTUP SEMUA FORM",
                "BUKA SEMUA FORM",
                "CETAK HASIL",
                "CREATE SURAT",
                "DELETE SURAT KETERANGAN",
                "CETAK SURAT",
              ],
            },
          ],
        },
      ],
    },
    {
      module: "Farmasi",
      subModules: [
        {
          name: "Panggil Antrian",
          allows: ["PANGGIL", "LEWATI", "VERIFIKASI", "PENYERAHAN OBAT"],
        },
        {
          name: "Resep Dokter",
          allows: [
            "READ",
            "UPDATE OBAT",
            "BATAL ORDER",
            "PINDAH LOKASI ORDER",
            "CETAK",
            "SIMPAN TELAAH",
            "VERIFIKASI",
            "EDIT OBAT",
            "SIMPAN EDIT",
            "OBAT DIGERUS",
            "SIMPAN & UBAH MENJADI RACIKAN",
            "BATAL",
            "(MENUNGGU PEMBAYARAN) CETAK",
            "(OBAT DISIAPKAN TUNAI) CETAK",
            "OBAT SIAP DISERAHKAN",
            "BATAL",
            "CETAK",
            "OBAT SIAP DISERAHKAN",
            "BATAL PENYERAHAN",
            "(PENYERAHAN OBAT) CETAK",
            "SERAHKAN OBAT",
          ],
        },
      ],
    },
  ]);

  // Return permissions data
  return {
    permissionsItem,
  };
});
